FROM python:3.7-buster
ENV FLASK_APP flasky.py
ENV FLASK_CONFIG docker
RUN useradd --create-home appuser
WORKDIR /home/flasky
USER flasky
COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
COPY . .
COPY flasky.py config.py boot.sh ./
# runtime configuration
EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
