FROM python:3.7.6

WORKDIR /usr/src/app

ENV FLASK_APP flasky.app
ENV FLASK_CONFIG development
ENV FLASK_ENV development
ENV MAIL_USERNAME bentestflask@gmail.com
ENV FLASKY_ADMIN bentestflask@gmail.com
ENV MAIL_PASSWORD gpz9dpkMUCy4yA6DCf2BPCEqHyWKu

COPY requirements.tx ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["flask", "run"]