"""empty message

Revision ID: 1012f8c95306
Revises: b5b9592a3d31
Create Date: 2019-10-07 21:31:45.906503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1012f8c95306'
down_revision = 'b5b9592a3d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    # ### end Alembic commands ###
