"""empty message

Revision ID: 258f7361f98c
Revises: 574a4603b233
Create Date: 2019-10-23 22:43:43.798112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258f7361f98c'
down_revision = '574a4603b233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
