"""empty message

Revision ID: 3fdfc12cfcc1
Revises: ee5352a4df27
Create Date: 2019-12-02 00:40:03.757480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdfc12cfcc1'
down_revision = 'ee5352a4df27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'activePost_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'activePost_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('active_posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
