"""empty message

Revision ID: 903de80645a4
Revises: e8e28972020e
Create Date: 2019-11-20 18:01:05.403052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903de80645a4'
down_revision = 'e8e28972020e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'published')
    # ### end Alembic commands ###
